### ISSUE TITLE
cannot use python3.6 in buildInputs

### ISSUE THREAD

**Issue by pedohorse** [cachix/nixpkgs-python#13]
you can test on simple 
```
mkShell {
    buildInputs = [ nixpkgs-python.packages.x86_64-linux."3.6" ];
};
```

then with `nix develop` - python will not start. 
looks like the problem has something to do with [this change since 3.8](https://docs.python.org/3/library/sys.html#sys.abiflags)

**Comment by domenkozar** [comment]
What error do you get?

**Comment by pedohorse** [comment]
sorry that i haven't posted the error message - thought it's easier to reproduce and see, but here it is:
```
Failed to import the site module
Traceback (most recent call last):
  File "/nix/store/3ydi8l8whzrvfbmr29aiyiahb9d2kqgs-python3-3.6.15/lib/python3.6/site.py", line 553, in <module>
    main()
  File "/nix/store/3ydi8l8whzrvfbmr29aiyiahb9d2kqgs-python3-3.6.15/lib/python3.6/site.py", line 539, in main
    known_paths = addusersitepackages(known_paths)
  File "/nix/store/3ydi8l8whzrvfbmr29aiyiahb9d2kqgs-python3-3.6.15/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/nix/store/3ydi8l8whzrvfbmr29aiyiahb9d2kqgs-python3-3.6.15/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/nix/store/3ydi8l8whzrvfbmr29aiyiahb9d2kqgs-python3-3.6.15/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/nix/store/3ydi8l8whzrvfbmr29aiyiahb9d2kqgs-python3-3.6.15/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/nix/store/3ydi8l8whzrvfbmr29aiyiahb9d2kqgs-python3-3.6.15/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/nix/store/3ydi8l8whzrvfbmr29aiyiahb9d2kqgs-python3-3.6.15/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata__linux_x86_64-linux-gnu'
```

as you see, there is `m` missing in `'_sysconfigdata__linux_x86_64-linux-gnu'`
and that has something to do with [this](https://docs.python.org/3/library/sys.html#sys.abiflags) i bet

**Comment by domenkozar** [comment]
Someone should try to apply https://github.com/pypa/distutils/pull/111/files and see if it fixes it.
